In [5]:
#Numpy is
#Collection
#Homogeneous
#Numerial Computing

In [7]:
import numpy as np

In [9]:
# single dimension
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [15]:
# Attribute
# Shape
# size
# dimension
# data type

In [19]:
# 2 dimension
y = np.array([[1,2],[3,4]])
print(y)

[[1 2]
 [3 4]]


In [21]:
print(x.shape)
print(y.shape)

(5,)
(2, 2)


In [23]:
print(x.size)
print(y.size)

5
4


In [25]:
print(x.ndim)
print(y.ndim)

1
2


In [27]:
print(x.dtype)
print(y.dtype)

int32
int32


- np.sum()
- np.min()
- np.max()
- np.mean()
- np.std()
- np.median()
- np.sort()
- np.prod()

In [30]:
x = np.array([5,4,7,9,11,2,12,1])

In [32]:
print(np.sum(x))

51


In [34]:
print(np.max(x))

12


In [36]:
print(np.mean(x))

6.375


In [38]:
print(np.median(x))

6.0


In [40]:
print(np.min(x))

1


In [42]:
print(np.std(x))

3.8058343369095824


In [44]:
print(np.sort(x))

[ 1  2  4  5  7  9 11 12]


In [50]:
print(np.percentile(x, 0.25))

1.0175


In [52]:
print(np.percentile(x, 0.75))

1.0525


### Array Aritjmatic
- np.add     (  +)
- np.multiply     ( *)
- np.subtract  (-)
- np.divide    (/)
- np.floor_divide  (//)
- np.mod      (%)
- np.power   

In [55]:
x = np.array([1,2,3,4,5])
y = np.array([9,8,7,6,5])

In [57]:
print(x+y)

[10 10 10 10 10]


In [62]:
print(np.multiply(x,y))

[ 9 16 21 24 25]


In [65]:
print(x*y)

[ 9 16 21 24 25]


In [69]:
print(np.power(x,2))

[ 1  4  9 16 25]


In [77]:
# Broadcasting operation
print(x+2)

[3 4 5 6 7]


In [79]:
# indexing
x = np.array([1,2,3,4,5])
print(x[3])

4


In [81]:
x[1] = 12
print(x)

[ 1 12  3  4  5]


In [87]:
# 2 dimension
a = np.array([[2,3,4],[5,6,7]])
print(a)

[[2 3 4]
 [5 6 7]]


In [89]:
print(a[0][1])

3


In [91]:
print(a[1][1])

6


In [93]:
print(a[0,1])

3


In [95]:
print(a[1,1])

6


In [101]:
# Slicing
x = np.array([5,3,2,7,9,8,1,0])

# syntax : x[startindex : stopindex : stepindex]

print(x[1:4])

[3 2 7]


In [103]:
print(x[1:8:2])

[3 7 8 0]


In [105]:
print(x[:4])

[5 3 2 7]


In [107]:
print(x[5:])

[8 1 0]


In [109]:
print(x[-1])

0


In [111]:
print(x[-3:])

[8 1 0]


In [113]:
print(x[-1: -4])

[]


In [115]:
print(x[-1 : -4 : -1])

[0 1 8]


In [117]:
print(x[-4 : -8 : -2])

[9 2]


In [119]:
print(x[-1 : -8 : -2])

[0 8 7 3]
